name: Linter and Tests

on:
  push:
      branches:
        - '**'
      tags:
        - '**'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install Lint
        run: poetry install

      - name: Run Lint
        run: poetry run flake8 gendiff

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Install package
        run: poetry install

      - name: Run Tests
        run: poetry run pytest
